version: '3.1'

services:
  mysql:
    restart: always
    image: mysql:8.0
    container_name: mysql8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: order
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
